# 每天零点运行一次，它会检查所有带有 "need reproduction" 标签的 Issues。如果这些 Issues 在过去的 3 天内没有任何活动，它们将会被自动关闭。这有助于保持 Issue 列表的整洁，并且提醒用户在必要时提供更多的信息。
name: Issue Close Require

# 触发条件：每天零点
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest

    steps:
      # 步骤1：关闭未活动的 Issues
      - name: Close Inactive Issues
        uses: actions-cool/issues-helper@v3
        with:
          actions: "close-issues" # 执行动作：关闭 Issues
          token: ${{ secrets.ACCESS_TOKEN }} # GitHub Token，用于认证
          labels: "need reproduction" # 目标标签
          inactive-day: 3 # 未活动天数阈值
